/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg = (uint32_t*)0x40020c14;

	//1. eneable the clock for GPIOD periperial on AHB1ENR bus
	//uint32_t temp = *pClkCtrlReg; //read operation
	//temp = temp | 0x08; //modify 1 bit (clock_EN bit)
	//*pClkCtrlReg = temp; //write back new value

	*pClkCtrlReg = *pClkCtrlReg | 0x08;
	//tak samo w wersji skróconej
	// *pClkCtrlReg |= 0x08; // C shortened notation
	// *pClkCtrlReg |= (1<<3); // SET 3rd bit position, left shift bit operator

	//2. configure the GPIOD mode
	//a. clear the 24th and 25th bit position (mode of GPIOD Port 12 ) (CLEAR)
	*pPortDModeReg &= 0xFCFFFFFF;
	//*pPortDModeReg &= ~(1 << 24);
	//*pPortDModeReg &= ~(1 << 25);
	// albo
	//*pPortDModeReg &= ~(3 << 24); //3 czyli 11 przesunieta o 24 stanie sie 1 na 25 i 24 bicie

	//b. make 24th bit position as 1 (SET)
	*pPortDModeReg |= 0x01000000;
	//	*pPortDModeReg |= (1 << 24);

	//3. set 12th bit of the output data register to make I/O pin 12 as HIGH
	*pPortDOutReg |= 0x1000;
	// *pPortDOutReg |= (1<<12);
	while(1);

    /* Loop forever */
	for(;;);
}
